name: .NET

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore HtmlToOpenXml.sln
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | cut -d "v" -f 2)
    - name: Build
      run: dotnet build --no-restore /p:Configuration=Release HtmlToOpenXml.sln
    - name: Test
      run: dotnet test ./test/HtmlToOpenXml.Tests/HtmlToOpenXml.Tests.csproj --verbosity n
    - name: Pack
      run: dotnet pack HtmlToOpenXml.sln -c Release -o ./artifacts -p:PackageVersion=${{ steps.get_version.outputs.VERSION }}
    - name: Push generated package to GitHub registry
      run: dotnet nuget push /home/runner/work/html2openxml/html2openxml/artifacts/HtmlToOpenXml.dll.${{ steps.get_version.outputs.VERSION }}.nupkg -k ${{secrets.NUGET_SECRET_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols true
